[package]
name = "demo"
version = "0.1.0"
authors = ["Nelson Herbin <nelson@herbin.info>"]
edition = "2018"

[library]

[dependencies]
microprofile = "0.0.2"
rand = "0.6.5"
regex = "1"
glob = "0.3.0"
colour = "0.6.0"
clap = "2.33.3"